### ISSUE TITLE
Reducers video is not by Rich anymore?

### ISSUE THREAD

**Issue by YurySolovyov** [tallesl/Rich-Hickey-fanclub#20]
When I click "Reducers - A Library and Model for Collection Processing (Jun 2012)" I'm getting "Dissecting Clojure Reducers"  by Renzo Borgatti

**Comment by tallesl** [comment]
Good catch, looks like they reused the URL and Hickey's talk got lost...
Replaced the link for an archive.org one with the original.

**Comment by YurySolovyov** [comment]
I wonder if that the same one: https://vimeo.com/45561411
